//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnosixWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InnosixEntities : DbContext
    {
        public InnosixEntities()
            : base("name=InnosixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountManager> AccountManager { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUsersTcClaim> AspNetUsersTcClaim { get; set; }
        public virtual DbSet<AspNetUsersToPortfolio> AspNetUsersToPortfolio { get; set; }
        public virtual DbSet<AspNetUsersToStage> AspNetUsersToStage { get; set; }
        public virtual DbSet<AspNetUsersToTC> AspNetUsersToTC { get; set; }
        public virtual DbSet<BusinessModel> BusinessModel { get; set; }
        public virtual DbSet<BusinessModelToTC> BusinessModelToTC { get; set; }
        public virtual DbSet<Cluster> Cluster { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Maturity> Maturity { get; set; }
        public virtual DbSet<Nace> Nace { get; set; }
        public virtual DbSet<Portfolio> Portfolio { get; set; }
        public virtual DbSet<PortfolioItem> PortfolioItem { get; set; }
        public virtual DbSet<PortfolioToPortfolioItem> PortfolioToPortfolioItem { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductToTC> ProductToTC { get; set; }
        public virtual DbSet<Revenue> Revenue { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesToTC> ServicesToTC { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<TCActive> TCActive { get; set; }
        public virtual DbSet<TCAdmin> TCAdmin { get; set; }
        public virtual DbSet<TCBasicInfo> TCBasicInfo { get; set; }
        public virtual DbSet<TCBusinessInfo> TCBusinessInfo { get; set; }
        public virtual DbSet<TCContact> TCContact { get; set; }
        public virtual DbSet<TCGeneral> TCGeneral { get; set; }
        public virtual DbSet<TCIdealPartner> TCIdealPartner { get; set; }
        public virtual DbSet<TCRating> TCRating { get; set; }
        public virtual DbSet<TCTechnology> TCTechnology { get; set; }
        public virtual DbSet<TechDomain> TechDomain { get; set; }
        public virtual DbSet<TechDomainToTC> TechDomainToTC { get; set; }
        public virtual DbSet<TechSector> TechSector { get; set; }
        public virtual DbSet<TechTag> TechTag { get; set; }
        public virtual DbSet<TechTagDeclined> TechTagDeclined { get; set; }
        public virtual DbSet<TechTagParents> TechTagParents { get; set; }
        public virtual DbSet<TechTagToTC> TechTagToTC { get; set; }
        public virtual DbSet<VTcClaim> VTcClaim { get; set; }
        public virtual DbSet<VTcWithTags> VTcWithTags { get; set; }
        public virtual DbSet<VTcWithTagsUser> VTcWithTagsUser { get; set; }
        public virtual DbSet<VUserTcClaim> VUserTcClaim { get; set; }
    
        public virtual ObjectResult<GetAdditionalTechTags_Result> GetAdditionalTechTags()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdditionalTechTags_Result>("GetAdditionalTechTags");
        }
    
        public virtual ObjectResult<GetTagHierarchy_Result> GetTagHierarchy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTagHierarchy_Result>("GetTagHierarchy");
        }
    }
}
