//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnosixWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCBusinessInfo
    {
        public long TCid { get; set; }
        public string BusinessSummary { get; set; }
        public string CompanyDescription { get; set; }
        public Nullable<int> NaceCodeId { get; set; }
        public Nullable<int> RevenueYear { get; set; }
        public Nullable<int> FullTimeEmployeesId { get; set; }
        public Nullable<int> FTEyear { get; set; }
        public string KeyCompetitors { get; set; }
        public string KeyPartners { get; set; }
        public string LargestOwners { get; set; }
        public Nullable<int> MaturityStageId { get; set; }
        public bool ProfitMaking { get; set; }
        public Nullable<int> RevenueId { get; set; }
        public int Established { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Maturity Maturity { get; set; }
        public virtual Nace Nace { get; set; }
        public virtual Revenue Revenue { get; set; }
        public virtual TCBasicInfo TCBasicInfo { get; set; }
    }
}
