//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnosixWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCTechnology
    {
        public long TCid { get; set; }
        public string AdditionalTechTags { get; set; }
        public string Patents { get; set; }
        public string OtherIpNotPatented { get; set; }
        public Nullable<int> TechnologySectorId { get; set; }
    
        public virtual TCBasicInfo TCBasicInfo { get; set; }
        public virtual TechSector TechSector { get; set; }
    }
}
