//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnosixWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechTagParents
    {
        public long Id { get; set; }
        public int TechTagId { get; set; }
        public int ParentTechTagId { get; set; }
    
        public virtual TechTag TechTag { get; set; }
        public virtual TechTag TechTag1 { get; set; }
    }
}
