//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnosixWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechTag()
        {
            this.TechTagParents = new HashSet<TechTagParents>();
            this.TechTagParents1 = new HashSet<TechTagParents>();
            this.TechTagToTC = new HashSet<TechTagToTC>();
        }
    
        public int Id { get; set; }
        public string TagName { get; set; }
        public Nullable<int> ParentsCount { get; set; }
        public Nullable<int> ChildrenCount { get; set; }
        public Nullable<int> UsageCount { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechTagParents> TechTagParents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechTagParents> TechTagParents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechTagToTC> TechTagToTC { get; set; }
    }
}
