//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnosixWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUserTcClaim
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string PhoneNumber { get; set; }
        public long TcId { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string CountryName { get; set; }
        public string CompanyEmail { get; set; }
        public string LegalSuffix { get; set; }
        public string CompanyWebsite { get; set; }
        public bool IsActive { get; set; }
    }
}
